name: "Ron Dyar"
#baseurl: 
# url: 
permalink: pretty
# exclude: 
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

#collections:
#  notes:
#    output: false  

defaults:
  -
    scope:
      path: ""
      #type: "notes"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
       is_post: true
      